"""
Proposal Agent - generate_pdf Lambda Action Group
Uses Claude via Bedrock to generate grant proposals, converts to PDF via fpdf2,
uploads to S3, returns pre-signed download URL.
"""
import json, logging, os, time, uuid
from datetime import datetime, timezone
from typing import Any
import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger()
logger.setLevel(logging.INFO)

bedrock_runtime = boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_REGION", "ap-south-1"))
s3_client = boto3.client("s3", region_name=os.environ.get("AWS_REGION", "ap-south-1"))
dynamodb = boto3.resource("dynamodb", region_name=os.environ.get("AWS_REGION", "ap-south-1"))

PROPOSALS_BUCKET = os.environ.get("PROPOSALS_BUCKET", "nidhiai-generated-pdfs")
PROPOSALS_TABLE = os.environ.get("DYNAMODB_PROPOSALS_TABLE", "nidhiai-proposals")
PROPOSAL_MODEL_ID = os.environ.get("PROPOSAL_MODEL_ID", "anthropic.claude-3-haiku-20240307-v1:0")


def build_proposal_prompt(grant: dict, ngo: dict) -> str:
    return f"""You are an expert grant proposal writer for Indian NGOs. Generate a professional CSR grant proposal as JSON.

GRANT: {grant.get('corporationName','Corp')} - {grant.get('programName','Program')}
Focus: {', '.join(grant.get('focusAreas',['social development']))}
Funding: Rs {grant.get('fundingRange',{}).get('min',200000):,} - Rs {grant.get('fundingRange',{}).get('max',1000000):,}

NGO: {ngo.get('ngoName','NGO')} | Sector: {ngo.get('sector','')} | PAN: {ngo.get('panCard','')}

Return ONLY valid JSON:
{{"executiveSummary":"200 words","organizationBackground":"150 words","problemStatement":"300 words with Indian statistics","proposedSolution":"400 words","budgetTable":[{{"category":"...","description":"...","amount":0,"justification":"..."}}],"impactMetrics":[{{"metric":"...","baseline":"...","target":"...","measurementMethod":"..."}}],"timeline":[{{"phase":"Phase 1","duration":"Month 1-3","milestones":["..."]}}],"conclusion":"150 words"}}

Budget must total within the funding range. Include 4+ impact metrics and 3 timeline phases. Use Indian context."""


def call_bedrock(prompt: str) -> str:
    """Call Bedrock. Claude uses invoke_model (Messages API), Nova uses converse() API."""
    is_claude = PROPOSAL_MODEL_ID.startswith("anthropic.")
    for attempt in range(3):
        try:
            if is_claude:
                body = {"anthropic_version":"bedrock-2023-05-31","max_tokens":4000,
                        "messages":[{"role":"user","content":prompt}],"temperature":0.7}
                resp = bedrock_runtime.invoke_model(
                    modelId=PROPOSAL_MODEL_ID,
                    body=json.dumps(body),
                    contentType="application/json", accept="application/json")
                return json.loads(resp["body"].read())["content"][0]["text"]
            else:
                # Nova and other models: use converse() API
                resp = bedrock_runtime.converse(
                    modelId=PROPOSAL_MODEL_ID,
                    messages=[{"role":"user","content":[{"text":prompt}]}],
                    inferenceConfig={"maxTokens":4000,"temperature":0.7})
                return resp["output"]["message"]["content"][0]["text"]
        except ClientError as e:
            if e.response["Error"]["Code"] == "ThrottlingException" and attempt < 2:
                time.sleep(2 ** attempt)
            else: raise
    raise RuntimeError("Bedrock failed")


def generate_pdf_bytes(content: dict, grant: dict, ngo: dict) -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        return f"PROPOSAL: {grant.get('programName','Grant')}\nBy: {ngo.get('ngoName','NGO')}\n{json.dumps(content,indent=2)}".encode()

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica","B",10); self.set_text_color(255,140,0)
            self.cell(0,8,"NidhiAI - Grant Proposal",align="R"); self.ln(5)
            self.set_draw_color(255,140,0); self.line(10,self.get_y(),200,self.get_y()); self.ln(3)
        def footer(self):
            self.set_y(-15); self.set_font("Helvetica","I",8); self.set_text_color(128,128,128)
            self.cell(0,10,f"Generated by NidhiAI | {datetime.now(timezone.utc).strftime('%B %d, %Y')} | Page {self.page_no()}",align="C")
        def section(self, title):
            self.set_font("Helvetica","B",13); self.set_text_color(30,60,114)
            self.set_fill_color(230,240,255); self.cell(0,9,f"  {title}",fill=True,ln=True)
            self.set_text_color(60,60,60); self.ln(3)
        def body(self, text):
            self.set_font("Helvetica","",10); self.set_text_color(60,60,60)
            self.multi_cell(0,6,str(text)); self.ln(4)

    pdf = PDF(); pdf.set_auto_page_break(auto=True, margin=20); pdf.add_page()

    # Title
    pdf.set_font("Helvetica","B",22); pdf.set_text_color(30,60,114); pdf.ln(10)
    pdf.multi_cell(0,12,"GRANT PROPOSAL",align="C")
    pdf.set_font("Helvetica","B",16); pdf.set_text_color(255,140,0)
    pdf.multi_cell(0,10,grant.get("programName","CSR Grant"),align="C")
    pdf.set_font("Helvetica","",12); pdf.set_text_color(80,80,80)
    pdf.multi_cell(0,8,f"To: {grant.get('corporationName','')} | By: {ngo.get('ngoName','')}",align="C")
    pdf.multi_cell(0,8,f"Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')} | PAN: {ngo.get('panCard','N/A')}",align="C")
    pdf.ln(8)

    # Sections
    sections = [("1. Executive Summary","executiveSummary"),("2. Organization Background","organizationBackground"),
                ("3. Problem Statement","problemStatement"),("4. Proposed Solution","proposedSolution")]
    for title, key in sections:
        pdf.section(title); pdf.body(content.get(key,""))

    # Budget table
    pdf.section("5. Budget Breakdown")
    budget = content.get("budgetTable",[])
    if budget:
        pdf.set_font("Helvetica","B",9); pdf.set_fill_color(30,60,114); pdf.set_text_color(255,255,255)
        pdf.cell(55,7,"Category",1,fill=True); pdf.cell(65,7,"Description",1,fill=True)
        pdf.cell(30,7,"Amount (Rs)",1,fill=True); pdf.cell(0,7,"Justification",1,fill=True,ln=True)
        pdf.set_font("Helvetica","",9); pdf.set_text_color(60,60,60); total=0
        for item in budget:
            amt = item.get("amount",0); total += amt
            pdf.cell(55,6,str(item.get("category",""))[:25],1)
            pdf.cell(65,6,str(item.get("description",""))[:30],1)
            pdf.cell(30,6,f"{amt:,.0f}",1); pdf.cell(0,6,str(item.get("justification",""))[:28],1,ln=True)
        pdf.set_font("Helvetica","B",9); pdf.set_fill_color(30,60,114); pdf.set_text_color(255,255,255)
        pdf.cell(120,7,"TOTAL",1,fill=True); pdf.cell(30,7,f"Rs {total:,.0f}",1,fill=True)
        pdf.cell(0,7,"",1,fill=True,ln=True); pdf.ln(5)

    # Impact metrics
    pdf.section("6. Impact Metrics")
    for m in content.get("impactMetrics",[]):
        pdf.set_font("Helvetica","",10); pdf.set_text_color(60,60,60)
        pdf.multi_cell(0,6,f"* {m.get('metric','')}: {m.get('baseline','')} -> {m.get('target','')} ({m.get('measurementMethod','')})"); pdf.ln(1)
    pdf.ln(3)

    # Timeline
    pdf.section("7. Timeline")
    for p in content.get("timeline",[]):
        pdf.set_font("Helvetica","B",10); pdf.cell(0,7,f"{p.get('phase','')} ({p.get('duration','')})",ln=True)
        pdf.set_font("Helvetica","",10)
        for ms in p.get("milestones",[]): pdf.multi_cell(0,6,f"  - {ms}")
        pdf.ln(2)

    # Conclusion + Declaration
    pdf.section("8. Conclusion"); pdf.body(content.get("conclusion",""))
    pdf.section("9. Declaration")
    pdf.body(f"We, {ngo.get('ngoName','')}, declare all information is accurate. Authorized Signatory: ___________  Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}")

    result = pdf.output(dest="S")
    return bytes(result) if not isinstance(result, bytes) else result


def lambda_handler(event: dict, context: Any) -> dict:
    logger.info(f"Event: {json.dumps(event)}")
    ag = event.get("actionGroup","generate_pdf"); ap = event.get("apiPath","/generate-proposal")

    try:
        props = event.get("requestBody",{}).get("content",{}).get("application/json",{}).get("properties",[])
        params = {p["name"]: p["value"] for p in props}
        grant = json.loads(params.get("grantData","{}")) if isinstance(params.get("grantData"), str) else params.get("grantData",{})
        ngo = json.loads(params.get("ngoProfile","{}")) if isinstance(params.get("ngoProfile"), str) else params.get("ngoProfile",{})
    except Exception as e:
        return _resp(ag, ap, {"status":"error","message":str(e)}, 400)

    try:
        raw = call_bedrock(build_proposal_prompt(grant, ngo))
        try:
            content = json.loads(raw[raw.find("{"):raw.rfind("}")+1])
        except: content = {"executiveSummary":raw[:500],"problemStatement":"See proposal.","proposedSolution":"Detailed in proposal.",
                          "budgetTable":[{"category":"Program","description":"Total","amount":500000,"justification":"As proposed"}],
                          "impactMetrics":[{"metric":"Beneficiaries","baseline":"0","target":"500","measurementMethod":"Count"}],
                          "timeline":[{"phase":"Phase 1","duration":"Month 1-6","milestones":["Start"]}],"conclusion":"Thank you."}

        pdf_bytes = generate_pdf_bytes(content, grant, ngo)
        pid = str(uuid.uuid4()); nid = ngo.get("ngoId","unknown"); gid = grant.get("grantId","unknown")
        s3_key = f"{nid}/proposals/{gid}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.pdf"

        s3_client.put_object(Bucket=PROPOSALS_BUCKET, Key=s3_key, Body=pdf_bytes, ContentType="application/pdf")
        url = s3_client.generate_presigned_url("get_object", Params={"Bucket":PROPOSALS_BUCKET,"Key":s3_key}, ExpiresIn=300)

        try:
            dynamodb.Table(PROPOSALS_TABLE).put_item(Item={"proposalId":pid,"ngoId":nid,"grantId":gid,"pdfS3Key":s3_key,"status":"generated","createdAt":datetime.now(timezone.utc).isoformat()})
        except: pass

        return _resp(ag, ap, {"status":"success","proposalId":pid,"downloadUrl":url,"s3Key":s3_key,
                             "summary":f"Proposal generated for {grant.get('programName','')} by {grant.get('corporationName','')}. Download ready.","content":content}, 200)
    except Exception as e:
        logger.exception(f"Failed: {e}")
        return _resp(ag, ap, {"status":"error","message":"Proposal generation failed. Please try again."}, 500)


def _resp(ag, ap, body, code):
    return {"messageVersion":"1.0","response":{"actionGroup":ag,"apiPath":ap,"httpMethod":"POST","httpStatusCode":code,
            "responseBody":{"application/json":{"body":json.dumps(body)}}}}
