"""
Impact Agent - generate_report Lambda Action Group
Generates quarterly impact reports for NGOs using Bedrock Claude.
Now includes PDF generation via fpdf2, uploads to S3, returns pre-signed URL.
"""
import json, logging, os, time, uuid
from datetime import datetime, timezone
from typing import Any
import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger()
logger.setLevel(logging.INFO)

bedrock_runtime = boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_REGION", "ap-south-1"))
s3_client = boto3.client("s3", region_name=os.environ.get("AWS_REGION", "ap-south-1"))
dynamodb = boto3.resource("dynamodb", region_name=os.environ.get("AWS_REGION", "ap-south-1"))

REPORTS_BUCKET = os.environ.get("REPORTS_BUCKET", "nidhiai-generated-pdfs")
MODEL_ID = os.environ.get("IMPACT_MODEL_ID", "anthropic.claude-3-haiku-20240307-v1:0")
NGO_PROFILES_TABLE = os.environ.get("DYNAMODB_NGO_PROFILES_TABLE", "nidhiai-ngo-profiles")


def fetch_ngo_profile(ngo_id: str) -> dict:
    """Fetch NGO profile from DynamoDB to fill in missing params."""
    if not ngo_id:
        return {}
    try:
        table = dynamodb.Table(NGO_PROFILES_TABLE)
        resp = table.get_item(Key={"ngoId": ngo_id})
        return resp.get("Item", {})
    except Exception as e:
        logger.warning(f"Could not fetch NGO profile for {ngo_id}: {e}")
        return {}


def call_bedrock(prompt: str) -> str:
    """Call Bedrock. Claude uses invoke_model (Messages API), Nova uses converse() API."""
    is_claude = MODEL_ID.startswith("anthropic.")
    for attempt in range(3):
        try:
            if is_claude:
                body = {"anthropic_version":"bedrock-2023-05-31","max_tokens":3000,
                        "messages":[{"role":"user","content":prompt}],"temperature":0.7}
                resp = bedrock_runtime.invoke_model(
                    modelId=MODEL_ID,
                    body=json.dumps(body),
                    contentType="application/json", accept="application/json")
                return json.loads(resp["body"].read())["content"][0]["text"]
            else:
                # Nova and other models: use converse() API
                resp = bedrock_runtime.converse(
                    modelId=MODEL_ID,
                    messages=[{"role":"user","content":[{"text":prompt}]}],
                    inferenceConfig={"maxTokens":3000,"temperature":0.7})
                return resp["output"]["message"]["content"][0]["text"]
        except ClientError as e:
            if e.response["Error"]["Code"] == "ThrottlingException" and attempt < 2:
                time.sleep(2 ** attempt)
            else: raise
    raise RuntimeError("Bedrock failed")


def generate_report_pdf(report: dict, ngo_name: str, period: str, beneficiaries: int, funds: int) -> bytes:
    """Generate a professional PDF impact report."""
    def fallback():
        text = f"IMPACT REPORT: {period}\nNGO: {ngo_name}\n\n"
        text += f"Executive Summary:\n{report.get('executiveSummary','')}\n\n"
        text += f"Beneficiary Demographics:\n{report.get('beneficiaryDemographics','')}\n\n"
        text += f"Success Stories:\n{report.get('successStories','')}\n\n"
        text += f"Challenges:\n{report.get('challenges','')}\n\n"
        text += f"Next Quarter Plans:\n{report.get('nextQuarterPlans','')}\n"
        return text.encode('utf-8')

    try:
        from fpdf import FPDF
    except ImportError:
        return fallback()

    try:
        class PDF(FPDF):
            def header(self):
                self.set_font("Helvetica","B",10); self.set_text_color(255,140,0)
                self.cell(0,8,"NidhiAI - Impact Report",align="R"); self.ln(5)
                self.set_draw_color(255,140,0); self.line(10,self.get_y(),200,self.get_y()); self.ln(3)
            def footer(self):
                self.set_y(-15); self.set_font("Helvetica","I",8); self.set_text_color(128,128,128)
                self.cell(0,10,f"Generated by NidhiAI Impact Agent | {datetime.now(timezone.utc).strftime('%B %d, %Y')} | Page {self.page_no()}",align="C")
            def section(self, title):
                self.set_font("Helvetica","B",13); self.set_text_color(30,60,114)
                self.set_fill_color(230,240,255); self.cell(0,9,f"  {title}",fill=True,ln=True)
                self.set_text_color(60,60,60); self.ln(3)
            def body(self, text):
                self.set_font("Helvetica","",10); self.set_text_color(60,60,60)
                safe_text = str(text).strip() or "N/A"
                self.multi_cell(0,6,safe_text); self.ln(4)

        pdf = PDF(); pdf.set_auto_page_break(auto=True, margin=20); pdf.add_page()

        # Title
        pdf.set_font("Helvetica","B",22); pdf.set_text_color(30,60,114); pdf.ln(10)
        pdf.multi_cell(0,12,"QUARTERLY IMPACT REPORT",align="C")
        pdf.set_font("Helvetica","B",16); pdf.set_text_color(255,140,0)
        pdf.multi_cell(0,10,str(period) or "Quarterly Report",align="C")
        pdf.set_font("Helvetica","",12); pdf.set_text_color(80,80,80)
        pdf.multi_cell(0,8,f"Organization: {str(ngo_name) or 'NGO'}",align="C")
        pdf.multi_cell(0,8,f"Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}",align="C")
        pdf.ln(8)

        # Key stats banner
        pdf.set_fill_color(30,60,114); pdf.set_text_color(255,255,255)
        pdf.set_font("Helvetica","B",10)
        pdf.cell(63,12,f"Beneficiaries: {beneficiaries:,}",1,fill=True,align="C")
        pdf.cell(63,12,f"Funds: Rs {funds:,}",1,fill=True,align="C")
        metrics = report.get("metrics",{})
        pdf.cell(0,12,f"Utilization: {metrics.get('fundUtilizationRate',85)}%",1,fill=True,align="C",ln=True)
        pdf.set_text_color(60,60,60); pdf.ln(6)

        # Sections
        sections = [
            ("1. Executive Summary","executiveSummary"),
            ("2. Beneficiary Demographics","beneficiaryDemographics"),
            ("3. Success Stories","successStories"),
            ("4. Challenges","challenges"),
            ("5. Next Quarter Plans","nextQuarterPlans"),
        ]
        for title, key in sections:
            val = report.get(key,"")
            if val:
                pdf.section(title); pdf.body(val)

        # Fund utilization table
        fund_util = report.get("fundUtilization",[])
        if fund_util:
            pdf.section("6. Fund Utilization Breakdown")
            pdf.set_font("Helvetica","B",9); pdf.set_fill_color(30,60,114); pdf.set_text_color(255,255,255)
            pdf.cell(70,7,"Category",1,fill=True); pdf.cell(50,7,"Amount (Rs)",1,fill=True)
            pdf.cell(0,7,"Percentage",1,fill=True,ln=True)
            pdf.set_font("Helvetica","",9); pdf.set_text_color(60,60,60)
            for item in fund_util:
                pdf.cell(70,6,str(item.get("category",""))[:35],1)
                pdf.cell(50,6,f"{item.get('amount',0):,}",1)
                pdf.cell(0,6,f"{item.get('percentage',0)}%",1,ln=True)
            pdf.ln(5)

        # Outcome highlights
        highlights = report.get("outcomeHighlights",[])
        if highlights:
            pdf.section("7. Key Outcomes")
            for h in highlights:
                pdf.set_font("Helvetica","",10)
                safe_h = str(h).strip() or "Highlight"
                pdf.multi_cell(0,6,f"  * {safe_h}"); pdf.ln(1)
            pdf.ln(3)

        # Declaration
        pdf.section("8. Declaration")
        pdf.body(f"This report has been prepared by {str(ngo_name) or 'NGO'} using the NidhiAI platform. "
                 f"All data presented reflects actual program activities during {str(period) or 'the period'}. "
                 f"Authorized Signatory: ___________  Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}")

        result = pdf.output(dest="S")
        return bytes(result) if not isinstance(result, bytes) else result
    except Exception as e:
        logger.error(f"FPDF2 error layout crash: {e}")
        return fallback()


def lambda_handler(event: dict, context: Any) -> dict:
    logger.info(f"Event: {json.dumps(event)}")
    ag = event.get("actionGroup", "generate_report")
    ap = event.get("apiPath", "/generate-report")

    try:
        props = event.get("requestBody",{}).get("content",{}).get("application/json",{}).get("properties",[])
        params = {p["name"]: p["value"] for p in props}

        ngo_id = params.get("ngoId", "")
        ngo_name = params.get("ngoName", "NGO")
        period = params.get("reportingPeriod", "Q4 2025")

        # Fetch real data from DynamoDB profile to fill missing params
        profile = fetch_ngo_profile(ngo_id) if ngo_id else {}
        sector = params.get("sector", profile.get("sector", "Education"))
        beneficiaries = int(params.get("beneficiariesServed", profile.get("beneficiariesServed", 500)))
        programs = int(params.get("programsCompleted", profile.get("programsCompleted", 3)))
        funds_utilized = int(params.get("fundsUtilized", profile.get("fundsUtilized", 300000)))
        geographic_reach = params.get("geographicReach", profile.get("geographicReach", "3 districts"))
        # Use profile name if Supervisor only passed ngoId
        if ngo_name == "NGO" and profile.get("ngoName"):
            ngo_name = profile["ngoName"]
    except Exception as e:
        return _resp(ag, ap, {"status":"error","message":str(e)}, 400)

    try:
        prompt = f"""Generate a quarterly CSR impact report in JSON for:
NGO: {ngo_name} | Sector: {sector} | Period: {period}
Data: {beneficiaries} beneficiaries, {programs} programs completed, Rs {funds_utilized:,} utilized, reach: {geographic_reach}

Return JSON:
{{"executiveSummary":"150 words","beneficiaryDemographics":"100 words","fundUtilization":[{{"category":"...","amount":0,"percentage":0}}],"outcomeHighlights":["..."],"successStories":"200 words","challenges":"100 words","nextQuarterPlans":"100 words","metrics":{{"totalBeneficiaries":{beneficiaries},"fundUtilizationRate":0,"programCompletionRate":0}}}}"""

        raw = call_bedrock(prompt)
        try:
            report = json.loads(raw[raw.find("{"):raw.rfind("}")+1])
        except:
            report = {"executiveSummary": raw[:500], "metrics": {"totalBeneficiaries": beneficiaries,
                      "fundUtilizationRate": 85, "programCompletionRate": 90}}

        report_id = str(uuid.uuid4())

        # Generate PDF and upload to S3
        pdf_bytes = generate_report_pdf(report, ngo_name, period, beneficiaries, funds_utilized)
        s3_key = f"{ngo_id}/reports/{period.replace(' ','_')}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.pdf"

        s3_client.put_object(Bucket=REPORTS_BUCKET, Key=s3_key, Body=pdf_bytes, ContentType="application/pdf")
        download_url = s3_client.generate_presigned_url("get_object", Params={"Bucket":REPORTS_BUCKET,"Key":s3_key}, ExpiresIn=300)

        summary = (f"Impact report generated for {ngo_name} ({period}). "
                   f"{beneficiaries} beneficiaries served, Rs {funds_utilized:,} utilized across {programs} programs.")

        return _resp(ag, ap, {"status":"success","reportId":report_id,"report":report,
                              "summary":summary,"downloadUrl":download_url,"s3Key":s3_key}, 200)
    except Exception as e:
        logger.exception(f"Failed: {e}")
        return _resp(ag, ap, {"status":"error","message":"Report generation failed."}, 500)


def _resp(ag, ap, body, code):
    return {"messageVersion":"1.0","response":{"actionGroup":ag,"apiPath":ap,"httpMethod":"POST","httpStatusCode":code,
            "responseBody":{"application/json":{"body":json.dumps(body)}}}}
